# very basic vendor bundle with missing settings


[vendor]
id = Komodo
name = komodo design
full_name = Komodo Design (C)
description = Internal print profiles for/nKomodo Design manufacturing
config_update_rest = Alohacajun/Komodo-Profiles
technologies = FFF
config_version = 0.0.2
config_update_url = 
changelog_url = 
slicer = SuperSlicer
slicer_version = 2.7.62.0

[printer_model:aprinter]
name = A Printer
variants = best
technology = FFF
family = 
bed_model = 
bed_texture = 
bed_with_grid = 0
thumbnail = 
default_materials = 

[printer:*common*]
gcode_flavor = marlin

[printer:bestprinter]
inherits = *common*
printer_variant = best
printer_model = aprinter

[print:*common*]
layer_height = 0.2

[print:0.2mm NORMAL]
inherits = *common*

[filament:*common*]
temperature = 200
[filament:*FF-ABS*]
filament_type = ABS
temperature = 260
bed_temperature = 110
default_fan_speed = 50


[filament:Basic ABS @Komodo]
inherits = *common*
